### ISSUE TITLE
Improve `triton-docker profile` output

### ISSUE THREAD

**Issue by misterbisson** [joyent/triton-docker-cli#10]
@trentm suggested in https://github.com/joyent/triton-docker-cli/pull/7#issuecomment-305839657

```
$ triton-docker profile
Name: east1
Account: trent.mick
Docker Host: tcp://us-east-1.docker.joyent.com:2376
Cert Path: /Users/trentm/.triton/docker/trent_mick@us-east-1_api_joyent_com

# Configured via env var; use `eval "$(triton env <profile name>)"` to change.
```

**Comment by trentm** [comment]
^^ And I'd put those extra lines (the empty line and the "# Configured ...") on *stderr*.  Then one can parse the output more reasonably: `triton-docker profile 2>/dev/null | grep Name | ...`.
