### ISSUE TITLE
triton-docker significantly slows down all commands

### ISSUE THREAD

**Issue by joshwilsdon** [joyent/triton-docker-cli#13]
For example:

```
stonehammer:~ joshw$ time /usr/local/bin/triton-docker-helper info 2>/dev/null | grep "^Name"
Name: us-east-3b

real    0m1.072s
user    0m0.048s
sys    0m0.018s
stonehammer:~ joshw$ time /usr/local/bin/triton-docker info 2>/dev/null | grep "^Name"
Name: us-east-3b

real    0m3.421s
user    0m1.878s
sys    0m0.242s
stonehammer:~ joshw$
```

shows that without the triton-docker wrapper, `info` takes 1 second, and with it, it takes 3.4 seconds. This seems unfortunate.

**Comment by misterbisson** [comment]
Yes, this is a known side effect of injecting data to make CNS useful. Please see https://github.com/joyent/triton-docker-cli#notes-and-cautions-about-cns-env-vars and the mention of CNS-164 and DOCKER-898. Performance can be improved when those are completed.

Fixing those is outside the scope of `triton-docker`, so I'm closing this.
