### ISSUE TITLE
Intercept unsupported commands and return a user-friendly error

### ISSUE THREAD

**Issue by misterbisson** [joyent/triton-docker-cli#15]
https://www.joyent.com/blog/optimizing-docker-on-triton#docker-commands-and-options-to-avoid suggests that there are a number of `docker` commands that aren't supported on Triton. `triton-docker` (even though it's just running Docker 1.12) should intercept attempts to run those commands and return a user-friendly error. The command spaces include:

- `triton-docker build`
- `triton-docker network create`
- `triton-docker network rm`
- `triton-docker volume`
- `triton-docker service`
- `triton-docker events`
- `triton-docker swarm`
- `triton-compose build`

There may be others as well

**Comment by bahamat** [comment]
Fixed in #25.
