### ISSUE TITLE
triton-compose should support newer docker-compose

### ISSUE THREAD

**Issue by jussisallinen** [joyent/triton-docker-cli#17]
Current version of triton-compose (docker-compose version 1.9.0, build 2585387) doesn't work well with LetsEncrypt (triton-dehydrated) certificates on OS X:

```
$ triton-compose ps
ERROR: SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

Newer docker-compose (docker-compose version 1.16.1, build 6d1ac21) works with LetsEncrypt certificates but image pull operations fail on Triton side:

```
latest: Pulling from autopilotpattern/vault (req afa6d532-a815-4d24-bb80-7882ac3b83d5)
ERROR: Error pulling image: Internal error (afa6d532-a815-4d24-bb80-7882ac3b83d5)
```

Task Summary on AdminUI shows:
```
pull_image_v2_layers
pullImageLayers failed - no successful create-docker-image
```

**Comment by jussisallinen** [comment]
To be exact atleast Brew docker-compose 1.16.1 doesn’t give the SSL error if that helps.

**Comment by jussisallinen** [comment]
Turned out fix for the certificate error was as easy as downloading newer cacert.pem from https://curl.haxx.se/docs/caextract.html
and doing export CURL_CA_BUNDLE=cacert.pem

**Comment by liftedkilt** [comment]
@jussisallinen - thanks for the workaround. That is very helpful.

**Comment by ghost** [comment]
+1 having this issue - would be nice if it was fixed officially

**Comment by teutat3s** [comment]
Happened here too. Workaround confirmed working. Thanks!
