### ISSUE TITLE
Quiet the "executing in" output

### ISSUE THREAD

**Issue by misterbisson** [joyent/triton-docker-cli#3]
From @trentm:

> - "Executing in" should very likely go to stderr to avoid getting stdout output that someone might want for something like `docker run ... | (expect just the output from my container)`.
> - One might want a `TRITON_DOCKER_QUIET=1` or whatever envvar to silence that "Executing in". I can see it being very helpful the first few times, but them for a lot of commands people will want it out of the way.

**Comment by misterbisson** [comment]
I'll add to this that we should look for `-q` args and silence on those as well. That will avoid this frustration:

```bash
$ triton rm $(triton-docker ps -a -q)
error: Invalid Parameters
error: no instance with name or short id "in" was found
error: Invalid Parameters
error: no instance with name or short id "set" was found
error: no instance with name or short id "at" was found
error: no instance with name or short id "to" was found
error: Invalid Parameters
error: no instance with name or short id "AM" was found
error: Invalid Parameters
error: no instance with name or short id "Executing" was found
error: no instance with name or short id "profile" was found
error: Invalid Parameters
error: Invalid Parameters
error: no instance with name or short id "use" was found
error: Invalid Parameters
Delete (async) instance 7503f84122cf (7503f841-22cf-6c44-e3b8-cc04670c6a03)
Delete (async) instance b3a003a52a5b (b3a003a5-2a5b-649c-e4a2-f1e06115fb95)
Delete (async) instance 8463159b37e9 (8463159b-37e9-e8b7-a231-81ec4c5164ee)
Delete (async) instance c913a9fc4878 (c913a9fc-4878-6800-9ba6-9690fba37391)
Delete (async) instance 745d2963823e (745d2963-823e-61d7-9191-dabe0416873e)
Delete (async) instance 5846a1dd2af5 (5846a1dd-2af5-e92e-bdb4-c89006482e9f)
Delete (async) instance 3bb84431a8fb (3bb84431-a8fb-4dd2-d086-d981d576585c)
triton instance delete: error: command failure
```

**Comment by trentm** [comment]
@misterbisson Or perhaps only have that "Executing in" info added to `triton-docker info` or a separate command?

I think trying to silence it based on option parsing will (a) be a game that you always lose sometimes and (b) will still leave cases where that output gets in the way.

FWIW, your example above would have been avoided with having the "Executing in" emitted to stderr. But I still think it would be annoying.

**Comment by tgross** [comment]
> @misterbisson Or perhaps only have that "Executing in" info added to triton-docker info or a separate command?

I'm :+1: on this option, fwiw. Happy to implement it myself if we're ok with that.
