### ISSUE TITLE
sudo all the things

### ISSUE THREAD

**Issue by jwreagor** [joyent/triton-docker-cli#6]
On a fresh system I performed the suggested...

```sh
$ sudo curl -o /usr/local/bin/triton-docker https://raw.githubusercontent.com/joyent/triton-docker-cli/master/triton-docker && chmod +x /usr/local/bin/triton-docker && ln -Fs /usr/local/bin/triton-docker /usr/local/bin/triton-compose && ln -Fs /usr/local/bin/triton-docker /usr/local/bin/triton-docker-install
```

...which returned...

```sh
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3482  100  3482    0     0  10081      0 --:--:-- --:--:-- --:--:-- 10092
chmod: changing permissions of '/usr/local/bin/triton-docker': Operation not permitted
```

Even though the error was only for `chmod`, using `sudo` for every step resulted in the behavior I anticipated.

```sh
$ sudo curl -o /usr/local/bin/triton-docker https://raw.githubusercontent.com/joyent/triton-docker-cli/master/triton-docker && sudo chmod +x /usr/local/bin/triton-docker && sudo ln -Fs /usr/local/bin/triton-docker /usr/local/bin/triton-compose && sudo ln -Fs /usr/local/bin/triton-docker /usr/local/bin/triton-docker-install
```

Is this a documentation error or was my blank ubuntu install doing something funky?

**Comment by jwreagor** [comment]
Actually, it's possible the reason was due to using a non-`root` user (`ubuntu`). 

Side note: Subsequent `sudo triton-docker-install` worked as expected.

**Comment by tgross** [comment]
Right, `sudo` applies for each step, not for whole thing. Although to be honest I'm not wild about that command line, as it `sudo`s a bunch of commands that are fetching from the network instead of just the ones we need. 

*Edit* oops, fouled that alternative up... just a sec.

**Comment by tgross** [comment]
Ah, nevermind... we're `curl`ing right into `/usr/local/bin` so we really do need to `sudo` on all the steps.
